scrape_configs:
  - job_name: cadvisor
    scrape_interval: 5s
    static_configs:
      - targets:
          - cadvisor:8080
  - job_name: "prometheus"
    # Override the global default and scrape targets from this job every 5 seconds.
    scrape_interval: 5s
    static_configs:
      - targets: ["localhost:9090"]
  - job_name: "node"
    # Override the global default and scrape targets from this job every 5 seconds.
    scrape_interval: 30s
    static_configs:
      - targets: ["node:8888"]
