name: CI Tests

on:
  push:
    branches-ignore:
      - master
      - staging

jobs:

  test-utils:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: make utils
      - run: make test-utils

  test-store:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: make store
      - run: make test-store

  test-contracts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: make contracts
      - run: make test-contracts

  test-cf:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: make cf-core
      - run: make test-cf

  test-watcher:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: make watcher
      - run: make test-watcher

  test-node:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: make node
      - run: make test-node

  test-integration:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: make pull-latest
      - run: make indra && make test-runner
      - run: make build-report
      - run: make start
      - run: make dls
      - run: make test-integration
      - name: Print logs
        if: failure()
        run: docker service logs --tail 200 indra_node && docker service logs --tail 200 indra_proxy
